services:
  dress-bot:
    build:
      context: bot
      dockerfile: Dockerfile
    env_file:
      - ./bot/.env
    volumes:
      - ./bot:/bot
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    restart: always
    depends_on:
      - redis

  redis:
    image: redis:7.2.3-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD:-password}
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:

